### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by onepack** [dmitrykazak/magento-google-tag-manager#2]
1 exception(s):
Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable in /home/server/domains/domain.com/public_html/vendor/dmitrykazak/magento-google-tag-manager/Model/Session.php on line 63

**Comment by dmitrykazak** [comment]
It was fixed for impression.

Thanks.

**Comment by secaliskan** [comment]
Hi Dmitry I have the same issue, just installed your module by composer
`{"message":"Warning: count(): Parameter must be an array or an object that implements Countable in \/home\/nova\/public_html\/vendor\/dmitrykazak\/magento-google-tag-manager\/Model\/Session.php on line 31"}`

**Comment by dmitrykazak** [comment]
Thanks @secaliskan 
It was fixed for PHP 7.2 (`count`)

**Comment by secaliskan** [comment]
Hi Dmitry, thanks much for quick fix. We are needing to set the datalayer properties and fields correctly for ecommerce tracking.
There's brand field in tag and when we select Manufacturer attribute as Brand, its showing 123 or 245 as the attribute code not value.
How we can show the attribute value instead of ID?  As Brand = 123 does not mean anything...

do you understamd what I mean?
now tag is showing (at product page)

`"ecommerce":     {
      "detail":       {
        "actionField":         {
          "list": "Health & Beauty"
        },
        "products":         [
          {
            "id": "NVP444298",
            "name": "Sweet Pea by Bath & Body Works",
            "price": "23.99",
            "category": "Health & Beauty",
            "brand": "1499",
            "path": "Health & Beauty/Personal Care"
          }
        ]`
I think this is because Manufacturer attribute is "Dropdown" in default and can not changeable to "Text".
So you should (I think) take the value instead of id of the attribute...

**Comment by dmitrykazak** [comment]
@secaliskan 0d6b51186fb9df0e4b6f6fcaf74927fd9a0a6e53
